/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.devTeam.motionConf.gui;

import fr.devTeam.motionConf.ParametersComponents;
import fr.devTeam.motionConf.model.BoxData;
import fr.devTeam.motionConf.model.BoxDataAdapter;
import fr.devTeam.motionConf.model.BoxDataEvent;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fanny
 */
public class BoxPanel extends javax.swing.JPanel {
    BoxData boxData = new BoxData();
    
    /**
     * Creates new form BoxPanel
     */
    public BoxPanel() {
        initComponents();
        initListeners();
        SerialSingleton.getInstance().getSerial().setBoxData(boxData);
        ParametersComponents.getInstance().setBoxTable(BoxTable);
    }
    
    public final void initListeners() {
        boxData.addBoxDataListener(new BoxDataAdapter() {
            @Override public void newBoxData (final BoxDataEvent ev) {
		SwingUtilities.invokeLater(new Runnable() {
		    @Override public void run() {
                        DefaultTableModel model = (DefaultTableModel)BoxTable.getModel();
                        int rows = model.getRowCount(); 
                        for(int i = rows - 1; i >=0; i--)
                        {
                           model.removeRow(i); 
                        }
                        String[] boxNames = ev.getBoxNames().getBoxNames();
                        int[] box = ev.getBox().getBoxes();
                        
                        for (int i=0; i< boxNames.length ; i++) {
                            model.addRow(new Object[]{boxNames[i],
                                new Boolean(intToBoolean(box[i] & 1)),
                                new Boolean(intToBoolean(box[i] & 2)), 
                                new Boolean(intToBoolean(box[i] & 4)),
                                new Boolean(intToBoolean(box[i] & 8)),
                                new Boolean(intToBoolean(box[i] & 16)), 
                                new Boolean(intToBoolean(box[i] & 32)),
                                new Boolean(intToBoolean(box[i] & 64)),
                                new Boolean(intToBoolean(box[i] & 128)), 
                                new Boolean(intToBoolean(box[i] & 256)),
                                new Boolean(intToBoolean(box[i] & 512)),
                                new Boolean(intToBoolean(box[i] & 1024)), 
                                new Boolean(intToBoolean(box[i] & 2048)),
                            });
                        }
                    }
		});
            }
        });
    }

    private boolean intToBoolean (int i) {
        
        return (i != 0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BoxTable = new javax.swing.JTable();

        BoxTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mode", "1L", "1M", "1H", "2L", "2M", "2H", "3L", "3M", "3H", "4L", "4M", "4H"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BoxTable);
        BoxTable.getColumnModel().getColumn(0).setMinWidth(50);
        BoxTable.getColumnModel().getColumn(1).setResizable(false);
        BoxTable.getColumnModel().getColumn(1).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(2).setResizable(false);
        BoxTable.getColumnModel().getColumn(2).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(3).setResizable(false);
        BoxTable.getColumnModel().getColumn(3).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(4).setResizable(false);
        BoxTable.getColumnModel().getColumn(4).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(5).setResizable(false);
        BoxTable.getColumnModel().getColumn(5).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(6).setResizable(false);
        BoxTable.getColumnModel().getColumn(6).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(7).setResizable(false);
        BoxTable.getColumnModel().getColumn(7).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(8).setResizable(false);
        BoxTable.getColumnModel().getColumn(8).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(9).setResizable(false);
        BoxTable.getColumnModel().getColumn(9).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(10).setResizable(false);
        BoxTable.getColumnModel().getColumn(10).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(11).setResizable(false);
        BoxTable.getColumnModel().getColumn(11).setPreferredWidth(2);
        BoxTable.getColumnModel().getColumn(12).setPreferredWidth(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BoxTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
