/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.devTeam.motionConf.gui;

/**
 *
 * @author EUGI7210
 */
public class MixagesPanel extends javax.swing.JPanel {

    /**
     * Creates new form MixagesPanel
     */
    public MixagesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MultiTypeComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        GimbalComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        auxChannelsGimbalCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        MovingAverageGimbalCheckBox = new javax.swing.JCheckBox();

        jLabel1.setText("Type :");

        MultiTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bi-rotor", "Tri-rotor", "QuadX", "Quad+", "Y4", "Vtail", "Y6", "Hexa6", "Hexa6X", "Hexa6H", "OctoX8", "OctoFlat+", "OctoFlatX" }));

        jLabel2.setText("Gimbal :");

        GimbalComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucune", "Standard", "Mix" }));

        jLabel3.setText("Canaux Aux :");
        jLabel3.setToolTipText("Si activé, les canaux AUX7 et AUX8 controllent l'inclinaison de la nacelle");

        auxChannelsGimbalCheckBox.setToolTipText("Si activé, les canaux AUX7 et AUX8 controllent l'inclinaison de la nacelle");

        jLabel4.setText("Lissage gimbal :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MultiTypeComboBox, 0, 90, Short.MAX_VALUE)
                        .addComponent(GimbalComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(auxChannelsGimbalCheckBox)
                    .addComponent(MovingAverageGimbalCheckBox))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MultiTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(GimbalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(auxChannelsGimbalCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MovingAverageGimbalCheckBox)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox GimbalComboBox;
    private javax.swing.JCheckBox MovingAverageGimbalCheckBox;
    private javax.swing.JComboBox MultiTypeComboBox;
    private javax.swing.JCheckBox auxChannelsGimbalCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
